### ISSUE TITLE
running the code 

### ISSUE THREAD

**Issue by threetwoone-w** [trqminh/rl-mapless-navigation#1]
I have a error when i am running the code:
arr = obj.__array_interface__ AttributeError: 'Image' object has no attribute '__array_interface__'
How should I modify it, please?

**Comment by trqminh** [comment]
Can you tell me which file cause the error?

**Comment by threetwoone-w** [comment]
The error is shown in figure：
![image](https://user-images.githubusercontent.com/37468836/144956545-54d16781-d7e8-478c-b204-3577226256a4.png)

**Comment by trqminh** [comment]
Can you help me to add a debug checkpoint before line 160 of `environment.py` and print out the type and the value of the `image` variable? So that I can help you with the errors.

**Comment by threetwoone-w** [comment]
> Can you help me to add a debug checkpoint before line 160 of `environment.py` and print out the type and the value of the `image` variable? So that I can help you with the errors.
The type print：
![Screenshot from 2021-12-07 11-10-14](https://user-images.githubusercontent.com/37468836/145019188-c3ec6017-cb82-40e3-98a1-98b41fb0f602.png)

The value print：
![Screenshot from 2021-12-07 11-11-35](https://user-images.githubusercontent.com/37468836/145019323-bc29ad60-70f8-4129-af2b-346a9440eeed.png)
Do you need a print like the figure above？

**Comment by trqminh** [comment]
I think it may be the conflict from the library that you are using. You can try to change the line to `fromarray(image.data)` and see if it works or not. If it still does not work, you can try to map the `image` to a numpy array.

**Comment by wxmshiguang** [comment]
I change the line to fromarray(image.data) but it does not work.
How do I convert ROS Message Image data to numpy array. I tried several methods and got it wrong.
Can you help me, thanks.

**Comment by threetwoone-w** [comment]
I have solved this problem and run successfully. Thank you very much for your advice.

**Comment by trqminh** [comment]
I am glad that you're now able to run the code. I hope that this repo is helpful for your work.
